/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5d790.vista;

import com.mycompany.parchisc5d790.controlador.ControladorPrincipal;
import javax.swing.JTextField;

/**
 *
 * @author UCR
 */
public class GUIGameOver extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIGameOver.class.getName());

    /**
     * Creates new form GUIWin
     */
    public GUIGameOver() {
        initComponents();
    }
    
        public GUIGameOver(ControladorPrincipal controlador) {
        initComponents();
        btnReiniciar.addActionListener(controlador);
        btnMenu.addActionListener(controlador);  
        
    }

    public String getTxtPuntaje() {
        return txtPuntaje.getText();
    }

    public String getTxtTiempo() {
        return txtTiempo.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPuntaje = new javax.swing.JTextField();
        txtTiempo = new javax.swing.JTextField();
        btnMenu = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPuntaje.setActionCommand("Puntaje");
        getContentPane().add(txtPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 200, -1));

        txtTiempo.setActionCommand("Tiempo");
        getContentPane().add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 200, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonInicio.png"))); // NOI18N
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        btnReiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonReiniciar.png"))); // NOI18N
        btnReiniciar.setBorderPainted(false);
        btnReiniciar.setContentAreaFilled(false);
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/panelGameOver.png"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JTextField txtPuntaje;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
