/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parchisc5d790.vista;

import com.mycompany.parchisc5d790.controlador.ControladorPrincipal;

/**
 *
 * @author Sham
 */
public class GUIInstrucciones extends javax.swing.JFrame {

    /**
     * Creates new form GUIInstrucciones
     */
    public GUIInstrucciones(ControladorPrincipal controlador) {
        initComponents();
        escuchar(controlador);
    }

        public void escuchar (ControladorPrincipal controlador){
        btnAtrasIns.addActionListener(controlador);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTexto = new javax.swing.JLabel();
        btnAtrasIns = new javax.swing.JButton();
        jlFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTexto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlTexto.setText("El juego se tiene que jugar de esta manera:");
        getContentPane().add(jlTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        btnAtrasIns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnAtrasIns.setActionCommand("AtrasInstrucciones");
        btnAtrasIns.setBorderPainted(false);
        btnAtrasIns.setContentAreaFilled(false);
        btnAtrasIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasInsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtrasIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, -1, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tableroInstrucciones.png"))); // NOI18N
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtrasInsActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasIns;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlTexto;
    // End of variables declaration//GEN-END:variables
}
