/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.parchisc5d790.vista;

import com.mycompany.parchisc5d790.controlador.ControladorJuego;
import com.mycompany.parchisc5d790.controlador.ControladorPrincipal;
import javax.swing.JButton;

/**
 *
 * @author Sham
 */
public class PanelControl extends javax.swing.JPanel {

    GUIJugador guiJugador;
    
    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
        //this.guiJugador=guiJugador;
        
    }
    
    
    public void escuchar(ControladorJuego controlador){
        btnAtras.addActionListener(controlador);
        btnDado.addActionListener(controlador);
        btnDetener.addActionListener(controlador);
         btnIniciar.addActionListener(controlador);
        btnPausar.addActionListener(controlador);
    
    }
    
     public void setJlNombreJugador1(String jlNombreJugador1) {
        this.jlNombreJugador1.setText(jlNombreJugador1);
    }

    public void setJlNombreJugador2(String jlNombreJugador2) {
        this.jlNombreJugador2.setText(jlNombreJugador2);
    }
    
        public String getJlTime() {
        return jlTime.getText();
    }

    public void setJlTime(String jlTime) {
        this.jlTime.setText(jlTime);
    }

    
    public void setColor(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnDado = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jlNombreJugador1 = new javax.swing.JLabel();
        jlNombreJugador2 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnPausar = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();
        jlTime = new javax.swing.JLabel();
        jlFondo = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dado1.1.png"))); // NOI18N
        btnDado.setActionCommand("Dado");
        btnDado.setBorderPainted(false);
        btnDado.setContentAreaFilled(false);
        btnDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadoActionPerformed(evt);
            }
        });
        add(btnDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonAtras.png"))); // NOI18N
        btnAtras.setActionCommand("AtrasJuego");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 650, -1, -1));

        jlNombreJugador1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlNombreJugador1.setText("Jugador 1");
        jlNombreJugador1.setToolTipText("");
        add(jlNombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        jlNombreJugador2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jlNombreJugador2.setText("Jugador 2");
        add(jlNombreJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));

        btnIniciar.setText("Iniciar");
        add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, -1, -1));

        btnPausar.setText("Pausar");
        add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 260, -1, -1));

        btnDetener.setText("Detener");
        add(btnDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, -1, -1));

        jlTime.setBackground(new java.awt.Color(153, 255, 51));
        jlTime.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlTime.setOpaque(true);
        add(jlTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 90, 70));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TableroFondo.png"))); // NOI18N
        add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlNombreJugador1;
    private javax.swing.JLabel jlNombreJugador2;
    private javax.swing.JLabel jlTime;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnDado() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
