/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.parchisc5d790.vista;

import com.mycompany.parchisc5d790.controlador.ControladorJuego;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Sham
 */
public class PanelJuego extends javax.swing.JPanel {
private ImageIcon tableroGrafico;
private ImageIcon ficha;
private ControladorJuego controlador;
    /**
     * Creates new form PanelJuego
     */
    public PanelJuego() {
        initComponents();
        tableroGrafico = new ImageIcon("./src/main/resources/img/tablerografico2.png");
        ficha = new ImageIcon("./src/main/resources/img/piecered.png");
    }

    public void escuchar(ControladorJuego controlador){
        this.controlador=controlador;
        addMouseListener(controlador);
    }
    
    public void paintComponent(Graphics g){
       super.paintComponent(g);
       tableroGrafico.paintIcon(this, g, 0, 0);
       if (controlador != null){
           controlador.dibujar(this, g);
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
